# Generated by Django 6.0 on 2026-01-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_de_nacimiento',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
