# Generated by Django 6.0 on 2026-01-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
