# Generated by Django 6.0 on 2026-01-21 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('curso', models.CharField(choices=[('SALA DE 5', 'Sala de 5'), ('1° GRADO', '1° Grado'), ('2° GRADO', '2° Grado'), ('3° GRADO', '3° Grado'), ('4° GRADO', '4° Grado'), ('5° GRADO', '5° Grado'), ('6° GRADO', '6° Grado'), ('1 AÑO', '1 Año'), ('2 AÑO', '2 Año'), ('3 AÑO', '3 Año'), ('4 AÑO', '4 Año'), ('5 AÑO', '5 Año'), ('6 AÑO', '6 Año')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(-2000)])),
                ('habilitada', models.CharField(default='NO', max_length=2)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
