# Generated by Django 6.0 on 2026-01-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumna',
            new_name='Cliente',
        ),
    ]
