# Generated by Django 6.0 on 2026-01-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0002_rename_alumna_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
