# Generated by Django 6.0 on 2025-12-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0002_alter_tarjeta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_activacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
