# Generated by Django 6.0 on 2026-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='curso',
            field=models.CharField(choices=[('SALA DE 5', 'Sala de 5'), ('1° GRADO', '1° Grado'), ('2° GRADO', '2° Grado'), ('3° GRADO', '3° Grado'), ('4° GRADO', '4° Grado'), ('5° GRADO', '5° Grado'), ('6° GRADO', '6° Grado'), ('1 AÑO', '1 Año'), ('2 AÑO', '2 Año'), ('3 AÑO', '3 Año'), ('4 AÑO', '4 Año'), ('5 AÑO', '5 Año'), ('6 AÑO', '6 Año')], max_length=10),
        ),
    ]
