# Generated by Django 6.0 on 2026-01-23 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='codigo',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
