# Generated by Django 6.0 on 2026-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='habilitada',
            field=models.CharField(default=False),
        ),
    ]
