# Generated by Django 6.0 on 2025-12-20 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0003_alter_tarjeta_fecha_activacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='alumna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosco.alumna'),
        ),
    ]
