# Generated by Django 6.0 on 2026-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0003_alter_tarjeta_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='habilitada',
            field=models.BooleanField(default=False),
        ),
    ]
