# Generated by Django 6.0 on 2025-12-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0004_alter_tarjeta_alumna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='ultima_modificacion',
            new_name='fecha_ultima_modificacion',
        ),
    ]
