# Generated by Django 6.0 on 2026-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0004_alter_tarjeta_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
