# Generated by Django 6.0.3 on 2026-03-11 03:37

import comedor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alm_por_sem', models.IntegerField(max_length=1)),
                ('nivel', models.CharField(choices=[('PRIMARIA/SECUNDARIA', 'Primaria/Secundaria'), ('JARDIN', 'Jardin')])),
                ('nro_de_cliente', models.IntegerField(max_length=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ValeDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('comentarios', models.CharField(blank=True, max_length=50, null=True)),
                ('comprobante', models.ImageField(upload_to=comedor.models.picture_upload_to, verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='ValeMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
                ('comentarios', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
