# Generated by Django 6.0.3 on 2026-03-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comedor', '0001_initial'),
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.colegio'),
        ),
        migrations.AddField(
            model_name='valediario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cliente'),
        ),
    ]
