# Generated by Django 6.0 on 2026-01-17 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiosco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.CharField(choices=[('CARGA', 'Carga'), ('COMPRA', 'Compra')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosco.tarjeta')),
            ],
        ),
    ]
