# Generated by Django 6.0 on 2026-01-22 23:41

import django.db.models.deletion
import transacciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiosco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(default=transacciones.models.generate_code, max_length=32, unique=True)),
                ('comprobante', models.ImageField(upload_to=transacciones.models.picture_upload_to, verbose_name='Comprobante')),
                ('estado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.CharField(choices=[('CARGA', 'Carga'), ('COMPRA', 'Compra')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosco.tarjeta')),
            ],
        ),
    ]
