# Generated by Django 6.0 on 2026-01-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
