# Generated by Django 6.0 on 2026-01-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_delete_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='detalle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
