# Generated by Django 6.0.3 on 2026-03-11 03:37

import django.core.validators
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=productos.models.picture_upload_to, verbose_name='Picture')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('ALFAJORES', 'Alfajores'), ('BEBIDAS', 'Bebidas'), ('GALLETITAS', 'Galletitas'), ('COMIDA', 'Comida'), ('CHOCOLATES', 'Chocolates'), ('CARAMELOS', 'Caramelos'), ('HELADOS', 'Helados')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('codigo_de_barras', models.CharField(max_length=13, unique=True)),
                ('code', models.CharField(default=productos.models.generate_code, max_length=32, unique=True)),
            ],
        ),
    ]
