# Generated by Django 6.0 on 2026-01-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ALFAJORES', 'Alfajores'), ('BEBIDAS', 'Bebidas'), ('GALLETITAS', 'Galletitas'), ('CHOCOLATES', 'Chocolates'), ('CARAMELOS', 'Caramelos'), ('HELADOS', 'Helados')], max_length=30),
        ),
    ]
