# Generated by Django 6.0 on 2026-01-14 22:38

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='picture',
            field=models.ImageField(default=1, upload_to=productos.models.picture_upload_to, verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
