# Generated by Django 6.0 on 2026-01-15 02:55

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='picture',
            field=models.ImageField(upload_to=productos.models.picture_upload_to, verbose_name='Picture'),
        ),
    ]
