# Generated by Django 6.0 on 2026-01-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barras',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
